import type { Review } from "@/types";

export const reviews: Review[] = [
  {
    id: "rv-1",
    name: "Hussain",
    country: "United Kingdom",
    countryCode: "GB",
    score: 9.4,
    title: "Far above its category",
    body: "Not a 3 star hotel — more on the side of a 4 star. The staff went above and beyond, and the room was immaculate. We will return.",
    travelType: "Couple",
    stayDate: "March 2025",
    createdAt: "2025-03-22",
  },
  {
    id: "rv-2",
    name: "Natasha",
    country: "United Kingdom",
    countryCode: "GB",
    score: 9.6,
    title: "Perfectly placed in Rabat",
    body: "Central and near a lot of restaurants, cafés, and shops — about 15 minutes to walk to the old Medina. Breakfast was excellent and the location unbeatable.",
    travelType: "Couple",
    stayDate: "February 2025",
    createdAt: "2025-02-14",
  },
  {
    id: "rv-3",
    name: "Laura",
    country: "Colombia",
    countryCode: "CO",
    score: 10,
    title: "Would stay every time I visit Rabat",
    body: "Everything works perfectly. I stayed for a whole week and didn't have the slightest problem. The rooms are well-equipped, modern, and very comfortable. The hotel is beautiful, and the location is perfect.",
    travelType: "Solo",
    stayDate: "January 2025",
    createdAt: "2025-01-30",
  },
  {
    id: "rv-4",
    name: "Ilona",
    country: "United Kingdom",
    countryCode: "GB",
    score: 9.2,
    title: "A unique, quieter neighbourhood",
    body: "Great location close to amenities and train station, close to tourist areas whilst also being a quieter neighbourhood. Loved being opposite a church as well — felt unique.",
    travelType: "Couple",
    stayDate: "December 2024",
    createdAt: "2024-12-19",
  },
  {
    id: "rv-5",
    name: "Polina",
    country: "Spain",
    countryCode: "ES",
    score: 9.0,
    title: "Friendly, accommodating, and convenient",
    body: "Great location, friendly staff. They switched the bed in our room per our request even though we did not stay long. Free parking — there was always a place available.",
    travelType: "Couple",
    stayDate: "November 2024",
    createdAt: "2024-11-07",
  },
  {
    id: "rv-6",
    name: "Adam",
    country: "Canada",
    countryCode: "CA",
    score: 9.5,
    title: "Genuine, attentive service",
    body: "Staff are very friendly. They always will try to help you if you have concerns. The cleaning team does an amazing job — they will even fold your clothes if they see them on the bed.",
    travelType: "Solo",
    stayDate: "October 2024",
    createdAt: "2024-10-22",
  },
  {
    id: "rv-7",
    name: "Emzar",
    country: "Georgia",
    countryCode: "GE",
    score: 9.8,
    title: "ALAE was wonderful",
    body: "We are very satisfied with our stay at AZ Hotel. The location is perfect, clean rooms, new and fresh hotel. The staff was perfect, especially ALAE — very attentive and kind.",
    travelType: "Family",
    stayDate: "September 2024",
    createdAt: "2024-09-15",
  },
  {
    id: "rv-8",
    name: "Waqar",
    country: "Ireland",
    countryCode: "IE",
    score: 9.1,
    title: "Najma was super helpful",
    body: "Location and cleanliness were outstanding. Staff member Najma was super helpful throughout our stay.",
    travelType: "Business",
    stayDate: "August 2024",
    createdAt: "2024-08-04",
  },
  {
    id: "rv-9",
    name: "Liz",
    country: "Canada",
    countryCode: "CA",
    score: 9.2,
    title: "Walkable to the train station",
    body: "Hotel was a short easy walk from the train station. Bright and clean. The restaurant and outside eating area were inviting. The beds were comfortable and well-appointed.",
    travelType: "Couple",
    stayDate: "July 2024",
    createdAt: "2024-07-12",
  },
  {
    id: "rv-10",
    name: "Shahid",
    country: "Pakistan",
    countryCode: "PK",
    score: 9.0,
    title: "Elegant, well-connected",
    body: "Nice and elegant hotel at a nice location. Access to public transport is good. The room was nice and clean, and the view from the room is lovely.",
    travelType: "Family",
    stayDate: "June 2024",
    createdAt: "2024-06-09",
  },
];

export const reviewCategories = [
  { label: "Staff",           score: 9.0 },
  { label: "Facilities",      score: 8.5 },
  { label: "Cleanliness",     score: 8.9 },
  { label: "Comfort",         score: 8.9 },
  { label: "Value for money", score: 8.4 },
  { label: "Location",        score: 9.3 },
  { label: "Free Wi-Fi",      score: 8.2 },
];
